name: argc-demo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - jupyter
  - pandas
  - tqdm
  - folium
  - matplotlib
  - mapclassify
  - streamlit
  - pip:
      - geopandas==0.13.2
      - selenium==4.11.2
